# syntax=docker/dockerfile:1

FROM golang:1.17-alpine

WORKDIR /app

# Copy the source code into the container
COPY * ./
RUN go mod download

# Build the app
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o /exodialib-core -v .

# deploy

FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /exodialib-core /exodialib-core

EXPOSE 9001

USER nonroot:nonroot

ENTRYPOINT [ "/exodialib-core", "init" ]